name: 'my_blog_analytics_dbt'
version: '1.0.0'

profile: 'my_blog_analytics_dw'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +dbt-osmosis: "schema/{model}.yml"
  +materialized: table