name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          cat <<EOF >> .env
          DBT_TARGET=dev
          DBT_GCP_PROJECT=${{ secrets.CI_GCP_PROJECT }}
          DBT_BIGQUERY_DATASET=${{ secrets.CI_BIGQUERY_DATASET }}
          EOF

      - name: Build Docker image
        run: docker build -t dbt-app .

      - name: Run sqlfluff lint
        run: |
          docker run --rm --env-file .env dbt-app sqlfluff lint ./dbt/models/