name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dbt-app .

      - name: Run sqlfluff lint
        env:
          DBT_GCP_PROJECT: ${{ secrets.CI_GCP_PROJECT }}
        run: docker run dbt-app sqlfluff lint ./dbt/models/